### PR TITLE
Add Office 2019 IDs

### PR DESCRIPTION
**Pull request by saltspork**

### CODE REVIEW

**Comment by TCB13** [comment]
Please merge! This closes #6

**Comment by ricktendo** [comment]
Yes, please update

**Comment by sooluck** [comment]
i found some key IDs from the orgin of KMS vlmscd,the author mentioned an branch of py kms,https://github.com/ThunderEX/py-kms.and from the author i've found the keys we need.https://github.com/ThunderEX/py-kms/blob/master/KmsDataBase.xml.
appid is the same with office2016
and other keys we could search these keys of office2016 to compare with office2019's.so that we can locate these keys we need.

**Comment by TCB13** [comment]
@sooluck what are you talking about? The keys are available on Microsoft's website.

**Comment by sooluck** [comment]
> @sooluck what are you talking about? The keys are available on Microsoft's website.

maybe we can add these keys into client.py and kmsbase.py so that we can activate office2019?

**Pull request merged**
