### PR TITLE
Docker multiarch

### PR DESCRIPTION
**Pull request by simonmicro**
* This will temporary break the docker builds, until I reconfigure the build properties inside the docker repo
* This will not modify the current tags, just add new - until the configuration is corrected (also inside the docker repo)
* Tested on `amd64` and `arm32v6`
* ANY further change of the Dockerfiles need to be done inside EVERY file for EVERY architecture from now on

This implements #92

### CODE REVIEW

**Comment by Simonmicro** [comment]
I object - according to https://docs.docker.com/engine/reference/builder/#maintainer-deprecated the `MAINTAINER` command is deprecated (and at the moment it is not even shown inside the docker manifests anymore). If you wish to be listed as maintainer I / you could use the `LABEL` (**I am very sorry, that I removed the command, but I thought it would be better to remove the deprecated stuff when I am at it...**). I did not do that, because from my perspective the git history is enough...

**Comment by 6ec123321** [comment]
ok, whatever you want, actually, I don't care who/how I/you).
Good job.
You are Right - Remove MAINTEINER command. "... the git history is enough".

**Comment by Simonmicro** [comment]
@6ec123321 Okay, thanks! I again emphasize that, if you wish, you can add yourself back using `LABEL`. I did **not** intended to claim your work as mine. But yeah, we'll see what @SystemRage thinks about that :grinning:, I hope he will just accept the PR soon...

**Comment by SystemRage** [comment]
Only one thing before merging, if you can remove gimp files.
png images are enough.

**Comment by Simonmicro** [comment]
@SystemRage Here you go!

**Pull request merged**
